# Generated by Django 5.1.4 on 2025-01-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_admin', models.IntegerField(null=True)),
                ('updated_admin', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
