# Generated by Django 5.1.4 on 2025-01-10 18:01

import core.services.file_service
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_salon', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('brand', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('mileage', models.FloatField()),
                ('region', models.IntegerField()),
                ('city', models.IntegerField()),
                ('price', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('description', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('[a-zA-Zа-яА-Я0-9]', 'Only alpha characters are allowed.'), django.core.validators.MaxLengthValidator(255)])),
                ('gearbox', models.IntegerField(null=True)),
                ('fuel', models.IntegerField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to=core.services.file_service.upload_advert_photo)),
                ('expired_at', models.DateTimeField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('auto_salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_salon.autosalonmodel')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.categorymodel')),
            ],
            options={
                'db_table': 'adverts',
            },
        ),
    ]
